### ISSUE TITLE
Clojure binding not working ,is bug?

### ISSUE THREAD

**Issue by rankyangel2014** [stuarthalloway/programming-clojure#14]
user=>(loop [x 5 result []]
			(do (println x result))
			(if (zero? x)
                 result
                (recur  (conj result x)   (dec x) )))
				
------------output-----------------------------------
5 []
[5] 4
ClassCastException clojure.lang.PersistentVector cannot be cast to java.lang.Num
ber  clojure.lang.Numbers.isZero (Numbers.java:92)

---------------
 why?

**Comment by replomancer** [comment]
You flipped arguments in your recur call. It should be:  
`(recur (dec x) (conj result x))`
In your code when x has a value of [5] calling (zero? x) or (zero? [5]) raises exception.

**Comment by rankyangel2014** [comment]
thanks  a lot ,

**Comment by rankyangel2014** [comment]
thanks a lot  -_-
